[amp]
liftCurrentThreshold = 0.0

servo.extendPulseMicro = 1900
servo.retractPulseMicro = 1500

[bling]

[climb]
maxSpeed = 0.5
lockWinchMicros = 1000;
unlockWinchMicros = 2000;

[drivetrain]
frontLeftAbsEncoderOffset  =   39.8
frontRightAbsEncoderOffset = -130.1
backLeftAbsEncoderOffset   =  -93.3
backRightAbsEncoderOffset  =  -32.3

swerve.turn.kP = 2.0
swerve.turn.kI = 0.01
swerve.turn.kD = 3.0

[gate]
openMicros  =  950
closeMicros = 1300

[intake]
intakeSpeed = 0.45
reverseSpeed = 0.2

[speaker]
shootSpeed = 4300
reverseSpeed = -500
distanceThreshold = 0.100
arbFeedForward = 9.0
